static const char* css PROGMEM=
"HTTP/1.1 200 OK\n"
"Content-Type: text/html\n"
"\n"
"body{font-size:200%; margin:60px 0px; padding:0px;text-align:center;}\n"
"h1{text-align: center;  font-family:Arial, \"Trebuchet MS\", Helvetica, sans-serif;}\n"
"h2{text-align: center;  font-family:Arial, \"Trebuchet MS\", Helvetica, sans-serif;}\n"
"a{text-decoration:none;width:75px;height:50px;\n"
"border-color:black;\n"
"border-top:2px solid;\n"
"border-bottom:2px solid;\n"
"border-right:2px solid;\n"
"border-left:2px solid;\n"
"border-radius:10px 10px 10px;\n"
"-o-border-radius:10px 10px 10px;\n"
"-webkit-border-radius:10px 10px 10px;\n"
"font-size:100%; font-family:\"Trebuchet MS\",Arial, Helvetica, sans-serif;\n"
"-moz-border-radius:10px 10px 10px;\n"
"background-color:#293F5E;\n"
"padding:8px;\n"
"text-align: center;}\n"
"a:link {color:white;}\n"  
"a:visited {color:white;}\n" 
"a:hover {color:white;}\n"  
"a:active {color:white;}\n"
;
